<?php
function adminExpiredNormalizeEpoch($value){$v=(int)$value;if($v>20000000000)$v=(int)floor($v/1000);return $v;}
function adminExpiredBaseWhere($older=false){$now=time();$cut=$now-259200;$ended="(COALESCE(o.expired_warned_at,0)>0 OR (COALESCE(o.expire_date,0)>0 AND ((o.expire_date<20000000000 AND o.expire_date<={$now}) OR (o.expire_date>=20000000000 AND o.expire_date<=".($now*1000)."))))";if(!$older)return $ended;return "(".$ended." AND ((COALESCE(o.expired_warned_at,0)>0 AND o.expired_warned_at<={$cut}) OR (COALESCE(o.expire_date,0)>0 AND ((o.expire_date<20000000000 AND o.expire_date<={$cut}) OR (o.expire_date>=20000000000 AND o.expire_date<=".($cut*1000).")))))";}
function adminExpiredPanelWhere($kind){return $kind==='pg'?"LOWER(s.type)='pasarguard'":"LOWER(s.type)<>'pasarguard'";}
function adminExpiredDbState($o){$now=time();$exp=adminExpiredNormalizeEpoch($o['expire_date']??0);$warn=(int)($o['expired_warned_at']??0);$dateEnded=$exp>0&&$exp<=$now;$at=$warn>0?$warn:($dateEnded?$exp:0);return ['ended'=>$warn>0||$dateEnded,'reason'=>$dateEnded?'تاریخ':'حجم/پنل','ended_at'=>$at];}
function adminExpiredFetch($kind='pg',$older=false,$limit=15,$offset=0){global $connection;$w=adminExpiredBaseWhere($older);$p=adminExpiredPanelWhere($kind);$sql="SELECT o.*,s.type AS server_type,COALESCE(si.title,s.type) AS server_title FROM orders_list o JOIN server_config s ON s.id=o.server_id LEFT JOIN server_info si ON si.id=o.server_id WHERE o.status=1 AND {$p} AND {$w} ORDER BY COALESCE(NULLIF(o.expired_warned_at,0),o.expire_date) DESC,o.id DESC LIMIT ".max(1,(int)$limit)." OFFSET ".max(0,(int)$offset);$r=$connection->query($sql);$out=[];if(!$r)return $out;while($o=$r->fetch_assoc()){$o['_expired']=adminExpiredDbState($o);$out[]=$o;}return $out;}
function adminExpiredCount($kind='pg',$older=false){global $connection;$w=adminExpiredBaseWhere($older);$p=adminExpiredPanelWhere($kind);$r=$connection->query("SELECT COUNT(*) c FROM orders_list o JOIN server_config s ON s.id=o.server_id WHERE o.status=1 AND {$p} AND {$w}");if(!$r)return 0;$x=$r->fetch_assoc();return(int)($x['c']??0);}
function adminDeleteExpiredOrder($id){global $connection;$st=$connection->prepare("SELECT o.*,s.type server_type FROM orders_list o JOIN server_config s ON s.id=o.server_id WHERE o.id=? LIMIT 1");$st->bind_param('i',$id);$st->execute();$o=$st->get_result()->fetch_assoc();$st->close();if(!$o)return[false,'اشتراک پیدا نشد'];$type=strtolower((string)$o['server_type']);$res=null;if($type==='pasarguard'&&function_exists('removePasarguardUser'))$res=removePasarguardUser((int)$o['server_id'],$o['remark']);elseif($type==='marzban')$res=deleteMarzban((int)$o['server_id'],$o['remark']);elseif((int)$o['inbound_id']>0)$res=deleteClient((int)$o['server_id'],(int)$o['inbound_id'],$o['uuid']??'0',1);else$res=deleteInbound((int)$o['server_id'],$o['uuid']??'0',1);if($res===null||(is_object($res)&&isset($res->success)&&$res->success===false))return[false,'حذف از پنل ناموفق بود'];$st=$connection->prepare("DELETE FROM orders_list WHERE id=?");$st->bind_param('i',$id);$st->execute();$ok=$st->affected_rows===1;$st->close();return[$ok,$ok?'حذف شد':'حذف دیتابیس ناموفق بود'];}
function adminExpiredKeyboard($kind,$older,$page){$per=15;$page=max(0,(int)$page);$count=adminExpiredCount($kind,$older);$items=adminExpiredFetch($kind,$older,$per,$page*$per);$rows=[];foreach($items as$o){$rows[]=[['text'=>'❌ '.($o['remark']?:('#'.$o['id'])).' | '.$o['_expired']['reason'],'callback_data'=>'expiredSubView'.$o['id'].'_'.$kind.'_'.($older?1:0).'_'.$page]];}if(!$items)$rows[]=[['text'=>'موردی پیدا نشد','callback_data'=>'deltach']];$nav=[];if($page>0)$nav[]=['text'=>'⬅️ قبلی','callback_data'=>'expiredSubsList_'.$kind.'_'.($older?1:0).'_'.($page-1)];if(($page+1)*$per<$count)$nav[]=['text'=>'بعدی ➡️','callback_data'=>'expiredSubsList_'.$kind.'_'.($older?1:0).'_'.($page+1)];if($nav)$rows[]=$nav;if($count>0)$rows[]=[['text'=>'🗑 حذف یکجای همه ('.$count.')','callback_data'=>'expiredSubsBulkAsk_'.$kind.'_'.($older?1:0)]];$rows[]=[['text'=>'🔙 بازگشت','callback_data'=>'expiredSubsKind_'.$kind]];return[json_encode(['inline_keyboard'=>$rows],JSON_UNESCAPED_UNICODE),$count];}
function handleExpiredSubscriptionsAdmin(){global$data,$from_id,$admin,$userInfo,$message_id,$connection;try{if(!($from_id==$admin||!empty($userInfo['isAdmin'])))return false;if($data==='expiredSubsAdmin'){$kb=json_encode(['inline_keyboard'=>[[['text'=>'🛡 اشتراک‌های پنل پاسارگاد','callback_data'=>'expiredSubsKind_pg']],[['text'=>'🖥 اشتراک‌های غیر پنل پاسارگاد','callback_data'=>'expiredSubsKind_other']],[['text'=>'🔙 بازگشت','callback_data'=>'managePanels']]]],JSON_UNESCAPED_UNICODE);smartSendOrEdit($message_id,"🗑 مدیریت اشتراک‌های تمام‌شده

نوع پنل را انتخاب کنید:",$kb);exit;}if(preg_match('/^expiredSubsKind_(pg|other)$/',$data,$m)){$k=$m[1];$t=$k==='pg'?'پنل پاسارگاد':'پنل‌های غیر پاسارگاد';$kb=json_encode(['inline_keyboard'=>[[['text'=>'📋 همه اشتراک‌های تمام‌شده','callback_data'=>'expiredSubsList_'.$k.'_0_0']],[['text'=>'⏳ تمام‌شده‌های بیشتر از ۳ روز','callback_data'=>'expiredSubsList_'.$k.'_1_0']],[['text'=>'🔙 بازگشت','callback_data'=>'expiredSubsAdmin']]]],JSON_UNESCAPED_UNICODE);smartSendOrEdit($message_id,"🗑 {$t}",$kb);exit;}if(preg_match('/^expiredSubsList_(pg|other)_([01])_(\d+)$/',$data,$m)){$k=$m[1];$o=(int)$m[2]===1;$p=(int)$m[3];[$kb,$c]=adminExpiredKeyboard($k,$o,$p);smartSendOrEdit($message_id,"🗑 تعداد: {$c}
هر صفحه ۱۵ اشتراک نمایش داده می‌شود.",$kb);exit;}if(preg_match('/^expiredSubView(\d+)_(pg|other)_([01])_(\d+)$/',$data,$m)){$id=(int)$m[1];$st=$connection->prepare("SELECT o.*,s.type server_type,COALESCE(si.title,s.type) server_title FROM orders_list o JOIN server_config s ON s.id=o.server_id LEFT JOIN server_info si ON si.id=o.server_id WHERE o.id=? LIMIT 1");$st->bind_param('i',$id);$st->execute();$o=$st->get_result()->fetch_assoc();$st->close();if(!$o){alert('پیدا نشد',true);exit;}$x=adminExpiredDbState($o);$at=$x['ended_at']?date('Y-m-d H:i',$x['ended_at']):'نامشخص';$kb=json_encode(['inline_keyboard'=>[[['text'=>'🗑 حذف این اشتراک','callback_data'=>'expiredSubDelete'.$id.'_'.$m[2].'_'.$m[3].'_'.$m[4]]],[['text'=>'🔙 بازگشت','callback_data'=>'expiredSubsList_'.$m[2].'_'.$m[3].'_'.$m[4]]]]],JSON_UNESCAPED_UNICODE);smartSendOrEdit($message_id,"🗑 اشتراک تمام‌شده

🆔 {$id}
👤 {$o['userid']}
🔮 {$o['remark']}
🖥 {$o['server_title']}
⚠️ {$x['reason']}
🕒 {$at}",$kb);exit;}if(preg_match('/^expiredSubDelete(\d+)_(pg|other)_([01])_(\d+)$/',$data,$m)){[$ok,$msg]=adminDeleteExpiredOrder((int)$m[1]);if(!$ok){alert($msg,true);exit;}[$kb,$c]=adminExpiredKeyboard($m[2],(int)$m[3]===1,(int)$m[4]);smartSendOrEdit($message_id,"✅ حذف شد
باقی‌مانده: {$c}",$kb);exit;}if(preg_match('/^expiredSubsBulkAsk_(pg|other)_([01])$/',$data,$m)){$c=adminExpiredCount($m[1],(int)$m[2]===1);$kb=json_encode(['inline_keyboard'=>[[['text'=>'✅ حذف همه ('.$c.')','callback_data'=>'expiredSubsBulkDo_'.$m[1].'_'.$m[2]]],[['text'=>'❌ انصراف','callback_data'=>'expiredSubsList_'.$m[1].'_'.$m[2].'_0']]]],JSON_UNESCAPED_UNICODE);smartSendOrEdit($message_id,"⚠️ {$c} اشتراک حذف شوند؟",$kb);exit;}if(preg_match('/^expiredSubsBulkDo_(pg|other)_([01])$/',$data,$m)){$k=$m[1];$o=(int)$m[2]===1;$ok=0;$fail=0;foreach(adminExpiredFetch($k,$o,25,0)as$x){[$d,$z]=adminDeleteExpiredOrder((int)$x['id']);$d?$ok++:$fail++;}$left=adminExpiredCount($k,$o);$kb=json_encode(['inline_keyboard'=>[$left>0?[['text'=>'ادامه حذف ('.$left.')','callback_data'=>'expiredSubsBulkDo_'.$k.'_'.($o?1:0)]]:[['text'=>'✅ پایان','callback_data'=>'expiredSubsKind_'.$k]],[['text'=>'🔙 بازگشت','callback_data'=>'expiredSubsList_'.$k.'_'.($o?1:0).'_0']]]],JSON_UNESCAPED_UNICODE);smartSendOrEdit($message_id,"✅ حذف: {$ok}
❌ ناموفق: {$fail}
📌 باقی: {$left}",$kb);exit;}}catch(Throwable$e){error_log('expired admin: '.$e->getMessage());alert('خطا ثبت شد',true);exit;}return false;}
